#=======================#=======================#=======================
# These params are common to all trainers and MUST be present
#=======================#=======================#=======================
optimizer: 
  type: RMSprop             
  params:
    lr: 0.1 # initial learning rate
    weight_decay : 0.0001
    alpha: 0.9            
    eps: 1.0         
    momentum: 0.9            
    centered: false

lr_schedule:
  type: StairLR
  params:
    300: 0.01
    400: 0.001
    600: 0.0001

dataloader:
  train:
    batch_size: null # If "sampler" is present this must be null
    shuffle: null # If "sampler" is present this MUST be null 
    num_workers: 8
  val:
    batch_size: 172
    shuffle: False
    num_workers: 8

num_epochs: 2000
device: cuda     

checkpoint:
  save:
    dir: ./checkpoints/facenet
    frequency: 5 # save a checkpoint every x epochs 
  load: 
    path: null
    backbone: True 
    loss: True
    scheduler: True
    optimizer: True
#=======================#=======================#=======================
