#=======================#=======================#=======================
# These params are common to all loss functions and MUST be present
#=======================#=======================#=======================
device: cuda
#=======================#=======================#=======================

#=======================#=======================#=======================
# These params are specific to the CenterLoss
#=======================#=======================#=======================
alpha: 1
use_bias: True
#=======================#=======================#=======================