#=======================#=======================#=======================
# These params are common to all loss functions and MUST be present
#=======================#=======================#=======================
device: cuda
#=======================#=======================#=======================

#=======================#=======================#=======================
# These params are specific to the CrossEntropyLoss
#=======================#=======================#=======================
label_smoothing: 0.1
use_bias: True
#=======================#=======================#=======================