#=======================#=======================#=======================
# These params are common to all loss functions and MUST be present
#=======================#=======================#=======================
device: cuda
#=======================#=======================#=======================

#=======================#=======================#=======================
# These params are specific to the MarginCosineProduct
#=======================#=======================#=======================
s: 30.0  # Scale factor for logits
m: 0.40  # Cosine margin subtracted from target class
#=======================#=======================#=======================