#=======================#=======================#=======================
# These params are common to all eval datasets and MUST be present
#=======================#=======================#=======================
eval_dir: "./data/lfw"
#=======================#=======================#=======================

#=======================#=======================#=======================
# These params are specific to the LFW dataset
#=======================#=======================#=======================
pairs_path: "./data/lfw/lfw_ann.txt"
#=======================#=======================#=======================