from .casia_webface_train_val_transformation_config import CasiaWebFaceTrainValTransformationConfig
from .vgg_face2_train_val_transformation_config import VGGFace2TrainValTransformationConfig

__all__ = ["CasiaWebFaceTrainValTransformationConfig", "VGGFace2TrainValTransformationConfig"]