#=======================#=======================#=======================
# These params are common to all backbones and MUST be present
#=======================#=======================#=======================
input_size: [160, 160]
embedding_size: 512
device: cuda
#=======================#=======================#=======================  

#=======================#=======================#=======================
# These params are specific to the InceptionResNetV1
#=======================#=======================#=======================
dropout_keep: 0.8
#=======================#=======================#=======================

