#=======================#=======================#=======================
# These params are common to all backbones and MUST be present
#=======================#=======================#=======================
input_size: [299, 299]
embedding_size: 512
device: cuda
#=======================#=======================#=======================  

#=======================#=======================#=======================
# These params are specific to the InceptionResNetV2
#=======================#=======================#=======================
k: 256
l: 256
m: 384
n: 384
dropout_keep: 0.8
#=======================#=======================#=======================

