#=======================#=======================#=======================
# These params are common to all backbones and MUST be present
#=======================#=======================#=======================
input_size: [112, 112]
embedding_size: 512
device: cuda
#=======================#=======================#=======================  

#=======================#=======================#=======================
# These params are specific to the MobileNetV3
#=======================#=======================#=======================
model_size: large  # Options: large, small
width_mult: 1.0
reduced_tail: false
dilated: false
#=======================#=======================#=======================