#=======================#=======================#=======================
# These params are specific to the AdaptiveEarlyStopper
#=======================#=======================#=======================
delta: 0.1
base_patience: 5
patience_increase_ratio: 0.8
#=======================#=======================#=======================